service: lambda-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2 #default: us-east-1
  stage: dev #default: dev
  environment:
    FOO: bar

functions:
  function1:
    handler: index.handler
