service: lambda-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2 #default: us-east-1
  stage: dev #default: dev
  environment:
    FOO: bar

functions:
  function1:
    handler: index.handler

  myfunction:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /test-get/{param}
          request:
            parameters:
              paths:
                param: true
              querystrings: #this is optional.
                foo: false
                bar: true
